name: arrivo

services:
  server:
    image: arrivo-server:latest
    container_name: server
    restart: always
    env_file: .env
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_DATA_DIR=${DATABASE_DATA_DIR}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_DIALECT=${DATABASE_DIALECT}
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 4g
        reservations:
          memory: 2g