name: Arrivo

services:
  database:
    container_name: database
    env_file: .env
    image: postgres:latest
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - ${DATABASE_DATA_DIR}
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}