INSERT INTO available_product (name, company_id)
VALUES
    ('Apple juice', 1),
    ('Banana pack 5kg', 1),
    ('Milk cartoons box 6 pcs', 1),
    ('Bread', 1),
    ('Orange juice 1L', 1),
    ('Rice bag 1kg', 1),
    ('Pasta pack 500g', 1),
    ('Chicken breast 1kg', 1),
    ('Eggs 12 pcs', 1),
    ('Butter 250g', 1),
    ('Cheddar cheese 200g', 1),
    ('Tomato sauce jar 500ml', 1),
    ('Coffee beans 1kg', 1),
    ('Green tea 100g', 1),
    ('Cereal box 750g', 1),
    ('Honey jar 500g', 1),
    ('Strawberry jam 300g', 1),
    ('Peanut butter 500g', 1),
    ('Mineral water 1.5L', 1),
    ('Sparkling water 1.5L', 1),
    ('Coca-Cola 2L bottle', 1),
    ('Frozen pizza', 1),
    ('Ice cream tub 1L', 1),
    ('Chocolate bar', 1)
    ON CONFLICT (name) DO NOTHING;
